services:
  db:
    image: postgres:15
    restart: always
    container_name: pgsql15
    environment:
      POSTGRES_PASSWORD: root123456 # 密码(注意修改)
      POSTGRES_USER: dev # 用户(默认:postgres)
      # POSTGRES_DB: dev # 数据库名(默认使用 POSTGRES_USER 的值)
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d/

  nestjs-api:
    # image: nestjs-api:latest
    build:
      context: .
      tags:
        - nestjs-api:latest
    container_name: nestjs-api
    ports:
      - 8080:3000
    depends_on:
      - db
    volumes:
      - ./config:/usr/local/app/config
      - ./logs:/usr/local/app/logs
